version: "3.8"

services:
  auth_overseer:
    image: python:3.9-slim
    container_name: Auth-Overseer
    ports:
      - "5069:5069"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        pip install --no-cache-dir -r requirements.txt &&
        python bot.py
      "
    environment:
      - PYTHONUNBUFFERED=1